language: php

php:
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

env:
  - SYMFONY_VERSION=V2.5.1
  - SYMFONY_VERSION=v2.5.2
  - SYMFONY_VERSION=v2.5.3
  - SYMFONY_VERSION=v2.5.4
  - SYMFONY_VERSION=v2.5.5
  - SYMFONY_VERSION=v2.5.6
#  - SYMFONY_VERSION=origin/2.0
  - SYMFONY_VERSION=origin/master

script: phpunit

notifications:
  email:
    - iman@imanpage.com

