language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=origin/master

script: phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

notifications:
  email:
    - iman@imanpage.com

