language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  - SYMFONY_VERSION="~2.4" ANCHOVY_VERSION="~2.0" SENSIO_FRAMEWORK_EXTRA_VERSION="~3.0"

before_install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-interaction --no-update
  - composer require anchovy/curl-bundle:${ANCHOVY_VERSION} --no-interaction --no-update
  - composer require sensio/framework-extra-bundle:${SENSIO_FRAMEWORK_EXTRA_VERSION} --no-interaction --dev --no-update

install:
  - composer install --no-interaction --dev --prefer-source

script: ./vendor/bin/phpunit
notifications:
  email:
    - iman@imanpage.com

