language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

#before_script:
#  - wget http://getcomposer.org/composer.phar
#  - php composer.phar install

before_script: composer install --dev

env:
  - SYMFONY_VERSION="2.4.*" SENSIO_FRAMEWORK_EXTRA_BUNDLE_VERSION="3.*"
  - SYMFONY_VERSION="2.5.*" SENSIO_FRAMEWORK_EXTRA_BUNDLE_VERSION="3.*"
#  - SYMFONY_VERSION=origin/2.0
  - SYMFONY_VERSION=origin/master

script: phpunit -c app/

notifications:
  email:
    - iman@imanpage.com

