language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

env:
  - SYMFONY_VERSION=v2.0.10
  - SYMFONY_VERSION=origin/2.0
  - SYMFONY_VERSION=origin/master

script: phpunit --coverage-text

notifications:
  email: iman@imanpage.com

