language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script: composer install --prefer-source

#env:
#  - SYMFONY_VERSION=V2.5.6
#  - SYMFONY_VERSION=origin/master

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

script: phpunit -c app

matrix:
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=dev-master

notifications:
  email:
#    - iman@imanpage.com

