language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  - SYMFONY_VERSION=2.3.* SENSIO_FRAMEWORK_EXTRA_VERSION="~3.0"
  - SYMFONY_VERSION=dev-master SENSIO_FRAMEWORK_EXTRA_VERSION="~3.0"

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer require sensio/framework-extra-bundle:${SENSIO_FRAMEWORK_EXTRA_VERSION} --no-interaction --dev --no-update

install:
  - composer install --no-interaction --dev --prefer-source

script: phpunit

notifications:
  email:
    - iman@imanpage.com

